# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-uconsole-sdr"
BBFILE_PATTERN_meta-uconsole-sdr = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-uconsole-sdr = "10"

LAYERDEPENDS_meta-uconsole-sdr = "core raspberrypi qt6-layer sdr-layer openembedded-layer"
LAYERSERIES_COMPAT_meta-uconsole-sdr = "kirkstone"
